// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEawkRlmU8lrBEvZHNeMIaYf-5GJz0ZCM',
    appId: '1:865101767388:web:af1acdf350bca81d724a19',
    messagingSenderId: '865101767388',
    projectId: 'fodos-fa158',
    authDomain: 'fodos-fa158.firebaseapp.com',
    storageBucket: 'fodos-fa158.firebasestorage.app',
    measurementId: 'G-8RKME1SXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgv-RDocSjizU5hS-WBXUYZ7TIirhThJI',
    appId: '1:865101767388:android:b97c712eedb8abe0724a19',
    messagingSenderId: '865101767388',
    projectId: 'fodos-fa158',
    storageBucket: 'fodos-fa158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kGUvFYAhLeqYXxMbBYs9sEpTc2tXORQ',
    appId: '1:865101767388:ios:0f25ccfe66f46ad7724a19',
    messagingSenderId: '865101767388',
    projectId: 'fodos-fa158',
    storageBucket: 'fodos-fa158.firebasestorage.app',
    iosBundleId: 'com.example.flutter1B32026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2kGUvFYAhLeqYXxMbBYs9sEpTc2tXORQ',
    appId: '1:865101767388:ios:0f25ccfe66f46ad7724a19',
    messagingSenderId: '865101767388',
    projectId: 'fodos-fa158',
    storageBucket: 'fodos-fa158.firebasestorage.app',
    iosBundleId: 'com.example.flutter1B32026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEawkRlmU8lrBEvZHNeMIaYf-5GJz0ZCM',
    appId: '1:865101767388:web:5370a95fd9e9082b724a19',
    messagingSenderId: '865101767388',
    projectId: 'fodos-fa158',
    authDomain: 'fodos-fa158.firebaseapp.com',
    storageBucket: 'fodos-fa158.firebasestorage.app',
    measurementId: 'G-RQS4KW5D6Q',
  );
}
